# Generated by Django 4.2 on 2024-10-15 14:11

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conference_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=800, message='Capacity must be less than 800')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='program',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'], message='Only PDF allowed')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', datetime.date(2024, 10, 15))), name='the_start_date_must_be_greater_or_equal_than_today_time'),
        ),
    ]
